### PR TITLE
Properly render help & error texts

### PR DESCRIPTION
**Pull request by Alexander-Jordan**
This will fix any issues related to help/error texts not displaying properly or duplication.

All changes are added to the changelog, and they are as listed below:

* Block `form_help`: Implement our own from parent theme, resolve issue with help class and element type
* Block `form_row`: Remove bad way of getting help text through `form.vars.attr.help_text`
* Block `form_row` & `choice_row`: Add `{{- form_errors(form) -}}` & `{{- form_help(form) -}}`
* Remove all `{{- block('form_errors') -}}` to avoid duplicated error messages

### CODE REVIEW

**Comment by Alexander-Jordan** [comment]
Before we merge, let's merge this first: #6 
Then we can adjust this branch and apply the rest of the changes

**Comment by johanwilfer** [comment]
I checked the source repro, did you create a PR back with the changes we made in this repro @Alexander-Jordan ?

**Comment by Alexander-Jordan** [comment]
I have now synced the two repos, and still keeping our changes that we have made.
So this PR now only adds the things missing related to the issue we had just recently, without making it hard to merge with the original repo :)

**Comment by johanwilfer** [comment]
Great!

**Pull request merged**
