### PR TITLE
row_attr option support

### PR DESCRIPTION
**Pull request by a-wojcik**
This PR adds support for [row_attr](https://symfony.com/doc/current/reference/forms/types/collection.html#row-attr) option. Using this option we can add attributes to form field root element (div.field).

### CODE REVIEW

**Comment by a-wojcik** [comment]
Hey @Alexander-Jordan 
I prepared small PR which adds `row_attr` support that we talked about today.
Please review and let me know what you think.
Thanks :slightly_smiling_face:

**Comment by johanwilfer** [comment]
I added some escaping, also in other places for attributes. I think @Alexander-Jordan is the one who knows this best so lets see what he thinks :)

**Comment by a-wojcik** [comment]
Hey! I have one more suggestion :slightly_smiling_face: 
Currently when we set `attr` option with `class` value on `ChoiceType` field, `class` name is added twice (1. to `<select>` element; 2. to its parent (`<div class="select">`).

We can fix it by removing ` ~ classes|join(' ')` from [line 33](https://github.com/sirvoy/twig-bulma-form-theme-bundle/blob/9f63caf5e7df22a78ac09245b7d70e3ab335feaa/views/Form/bulma_layout.html.twig#LL33C65-L33C84).
Of course we have to be very careful with that :slightly_smiling_face: 
Let me know what you think.

very-unique-selector

**Comment by Alexander-Jordan** [comment]
> Hey! I have one more suggestion slightly_smiling_face Currently when we set `attr` option with `class` value on `ChoiceType` field, `class` name is added twice (1. to `<select>` element; 2. to its parent (`<div class="select">`).
> 
> We can fix it by removing ` ~ classes|join(' ')` from [line 33](https://github.com/sirvoy/twig-bulma-form-theme-bundle/blob/9f63caf5e7df22a78ac09245b7d70e3ab335feaa/views/Form/bulma_layout.html.twig#LL33C65-L33C84). Of course we have to be very careful with that slightly_smiling_face Let me know what you think.
> 
> very-unique-selector

@a-wojcik I think this is not a bad suggestion, but I looked into it and this is the background to why I think this should not be changed:

1) How selects specifically should be rendered can be viewed here: https://bulma.io/documentation/form/select/
This shows that if we want to manipulate the look of the selects using classes, we should add the classes to the parent wrapper of the select tag (a div), not to the select tag itself.
So this is the behavior we have right now, giving us the option to add a color or a specific size to the select.
We can do this by adding `'attr' => ['class' => 'is-small is-success']`, and it will be added to the parent `div` element wrapper.
This would stop working if we removed `~ classes|join(' ')` from line 33, so this is actually not the problem.

2) Inside the parent wrapper (the div) on line 34 we call for the parent block of `choice_widget_collapsed` with: `{{- parent() -}}`.
This does multiple things, but one specific thing is rendering the `widget_attributes` block to the select tag:
`<select {{ block('widget_attributes') }}{% if multiple %} multiple="multiple"{% endif %}>`.
(look at `form_div_layout.html.twig` at line 62)
This adds for example id & name (something we need).
But also classes if any are added to the `attr`.
This is the "problem", but then my question is: is this really a problem?
Bulma classes will not have an effect on the select tag when applied there, and if we want a unique identifier we should use the `id` attribute, which is already added to the select tag.

If we then have an example of an issue where we need to just add the classes to the parent div wrapper and not to the select tag, then one solution would be to clear the `form.vars.attr.class` after adding it on the parent wrapper.
That would look something like:
```
    {% set classes = form.vars.attr.class|default('') %}
    <div {{ block('form_widget_container_attributes') }}>
        <div class="{{ ('select ' ~ (multiple ? 'is-multiple ') ~ classes|join(' '))|trim }}">
            {% set form.vars.attr.class = '' %}
            {{- parent() -}}
        </div>
    </div>
```
So before we render the parent() block, reset the class attribute to an empty string.

Even if this is a solution, I think it is good to first consider if this is even necessary :)

**Review by Alexander-Jordan — APPROVED** [review]
Adjusted a bit to utilize the `attributes`-block defined at the parent form theme (`form_div_layout.html.twig`).
I left a comment about other added features as well, please have a look at them too.
Tested locally as well, this looks good to me now :)

**Review by johanwilfer — APPROVED** [review]
Looks great!

**Comment by a-wojcik** [comment]
Good job @Alexander-Jordan

**Pull request merged**
